defmodule ExGrib.Grib2.Section4.Templates.CategoricalForecastsAtIntervals do
  @moduledoc """
  Template 4.91

  Categorical forecasts at intervalstal level or in a horizontallayer in a continuous or non continuous time interval

  Notes:
  (1) Hours greater than 65534 will be coded as 65534.

  (2) The reference time in section 1 and the forecast time together define the beginning of the overall time interval.

  (3) An increment of zero means that the statistical processing the result of continuous (or near continuous) process,
    not the processing of a number of discrete samples. Examples of such continuous process are the temperatures measured
    by analogue maximum and minimum thermometers or thermographs and the rainfall measured by a rain guage. The reference
    and forecast times are successively set to their initial values plus or minus the increment, as defined by the type of
    time increment (one of octets (60+12(NC-1)), (73+12(NC-1)), (85+12(NC-1))...) For all but the innermost (last) time
    range, the next inner range is then precessed using these reference and forecast times as the initial reference and
    forecast time.

  WARNING THIS TEMPLATE WAS AUTOGENERATED AND IS LIKELY INCOMPLETE

  https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_temp4-91.shtml
  """

  defstruct parameter_category: nil,
            parameter_number: nil,
            type_of_generating_process: nil,
            background_generating_process_identifier: nil,
            analysis_or_forecast_generating_process_identifier: nil,
            hours_after_reference_time_of_data_cutoff: nil,
            minutes_after_reference_time_of_data_cutoff: nil,
            indicator_of_unit_of_time_range: nil,
            forecast_time_in_units_defined_by_octet: nil,
            type_of_first_fixed_surface: nil,
            scale_factor_of_first_fixed_surface: nil,
            scaled_value_of_first_fixed_surface: nil,
            type_of_second_fixed_surfaced: nil,
            scale_factor_of_second_fixed_surface: nil,
            scaled_value_of_second_fixed_surfaces: nil,
            nc_number_of_categories: nil,
            code_figure: nil,
            type_of_interval_for_first_and_second_limit: nil,
            scale_factor_of_first_limit: nil,
            scale_value_of_first_limit: nil,
            scale_factor_of_second_limit: nil,
            scale_value_of_second_limit: nil,
            year_of_end_of_overall_time_interval: nil,
            month_of_end_of_overall_time_interval: nil,
            day_of_end_of_overall_time_interval: nil,
            hour_of_end_of_overall_time_interval: nil,
            minute_of_end_overall_time_interval: nil,
            second_of_end_of_overall_time_interval: nil,
            n_number_of_time_range_specifications_describing_the_time_intervals_used_to_calculate_the_statistically_processed_field:
              nil,
            total_number_of_data_values_missing_in_the_statistical_process: nil,
            statistical_process_used_to_calculate_the_processed_field_from_the_field_at_each_time_increment_during_the_time_range:
              nil,
            type_of_time_increment_between_successive_fields_used_in_the_statistical_processing:
              nil,
            indicator_of_unit_of_time_range_over_which_statistical_processing_is_done: nil,
            length_of_the_time_range_over_which_statistical_processing_is_done_in_units_defined_by_the_previous_octet:
              nil,
            indicator_of_unit_of_time_for_the_increment_between_the_successive_fields_used: nil,
            time_increment_between_successive_fields_in_units_defined_by_the_previous_octet: nil,
            as_octets: nil

  @spec get(binary()) :: no_return
  def get(<<
        # Parameter category (see Code table 4.1)
        parameter_category::integer(),
        # Parameter number (see Code table 4.2)
        parameter_number::integer(),
        # Type of generating process (see Code table 4.3)
        type_of_generating_process::integer(),
        # Background generating process identifier (defined by originating centre)
        background_generating_process_identifier::integer(),
        # Analysis or forecast generating process identifier (see Code ON388 Table A)
        analysis_or_forecast_generating_process_identifier::integer(),
        # Hours after reference time of data cutoff (see Note 1)
        hours_after_reference_time_of_data_cutoff::integer-size(16),
        minutes_after_reference_time_of_data_cutoff::integer(),
        # Indicator of unit of time range (see Code table 4.4)
        indicator_of_unit_of_time_range::integer(),
        # Forecast time in units defined by octet 18 (see Note 2)
        forecast_time_in_units_defined_by_octet::integer-size(32),
        # Type of first fixed surface (see Code table 4.5)
        type_of_first_fixed_surface::integer(),
        scale_factor_of_first_fixed_surface::integer(),
        scaled_value_of_first_fixed_surface::integer-size(32),
        # Type of second fixed surfaced (see Code table 4.5)
        type_of_second_fixed_surfaced::integer(),
        scale_factor_of_second_fixed_surface::integer(),
        scaled_value_of_second_fixed_surfaces::integer-size(32),
        # NC - Number of Categories
        nc_number_of_categories::integer(),
        code_figure::integer-size(28880),
        # Type of interval for first and second limit (see Code table 4.91)
        type_of_interval_for_first_and_second_limit::integer-size(29680),
        scale_factor_of_first_limit::integer-size(30480),
        scale_value_of_first_limit::integer-size(2408),
        scale_factor_of_second_limit::integer-size(34480),
        scale_value_of_second_limit::integer-size(2408),
        year_of_end_of_overall_time_interval::integer-size(808),
        month_of_end_of_overall_time_interval::integer-size(40080),
        day_of_end_of_overall_time_interval::integer-size(40880),
        hour_of_end_of_overall_time_interval::integer-size(41680),
        minute_of_end_overall_time_interval::integer-size(42480),
        second_of_end_of_overall_time_interval::integer-size(43280),
        # n ― number of time range specifications describing the time intervals used to calculate the statistically-processed field
        n_number_of_time_range_specifications_describing_the_time_intervals_used_to_calculate_the_statistically_processed_field::integer-size(
          44080
        ),
        total_number_of_data_values_missing_in_the_statistical_process::integer-size(2408),
        # Statistical process used to calculate the processed field from the field at each time increment during the time range (see Code Table 4.10)
        statistical_process_used_to_calculate_the_processed_field_from_the_field_at_each_time_increment_during_the_time_range::integer-size(
          48080
        ),
        # Type of time increment between successive fields used in the statistical processing (see Code Table 4.11)
        type_of_time_increment_between_successive_fields_used_in_the_statistical_processing::integer-size(
          48880
        ),
        # Indicator of unit of time range over which statistical processing is done (see Code Table 4.4)
        indicator_of_unit_of_time_range_over_which_statistical_processing_is_done::integer-size(
          49680
        ),
        length_of_the_time_range_over_which_statistical_processing_is_done_in_units_defined_by_the_previous_octet::integer-size(
          2408
        ),
        # Indicator of unit of time for the increment between the successive fields used (see Code Table 4.4)
        indicator_of_unit_of_time_for_the_increment_between_the_successive_fields_used::integer-size(
          53680
        ),
        # Time increment between successive fields in units defined by the previous octet (see Note 3)
        time_increment_between_successive_fields_in_units_defined_by_the_previous_octet::integer-size(
          2408
        ),
        # As octets 60 to 71 next innermost step of processing
        as_octets::integer-size(8808),
        # Additional time range specifications included in accordance with the value of n Contents as octets 50 to 61 repeated as necessary.
        rest::binary()
      >>) do
    template = %__MODULE__{
      parameter_category: parameter_category,
      parameter_number: parameter_number,
      type_of_generating_process: type_of_generating_process,
      background_generating_process_identifier: background_generating_process_identifier,
      analysis_or_forecast_generating_process_identifier:
        analysis_or_forecast_generating_process_identifier,
      hours_after_reference_time_of_data_cutoff: hours_after_reference_time_of_data_cutoff,
      minutes_after_reference_time_of_data_cutoff: minutes_after_reference_time_of_data_cutoff,
      indicator_of_unit_of_time_range: indicator_of_unit_of_time_range,
      forecast_time_in_units_defined_by_octet: forecast_time_in_units_defined_by_octet,
      type_of_first_fixed_surface: type_of_first_fixed_surface,
      scale_factor_of_first_fixed_surface: scale_factor_of_first_fixed_surface,
      scaled_value_of_first_fixed_surface: scaled_value_of_first_fixed_surface,
      type_of_second_fixed_surfaced: type_of_second_fixed_surfaced,
      scale_factor_of_second_fixed_surface: scale_factor_of_second_fixed_surface,
      scaled_value_of_second_fixed_surfaces: scaled_value_of_second_fixed_surfaces,
      nc_number_of_categories: nc_number_of_categories,
      code_figure: code_figure,
      type_of_interval_for_first_and_second_limit: type_of_interval_for_first_and_second_limit,
      scale_factor_of_first_limit: scale_factor_of_first_limit,
      scale_value_of_first_limit: scale_value_of_first_limit,
      scale_factor_of_second_limit: scale_factor_of_second_limit,
      scale_value_of_second_limit: scale_value_of_second_limit,
      year_of_end_of_overall_time_interval: year_of_end_of_overall_time_interval,
      month_of_end_of_overall_time_interval: month_of_end_of_overall_time_interval,
      day_of_end_of_overall_time_interval: day_of_end_of_overall_time_interval,
      hour_of_end_of_overall_time_interval: hour_of_end_of_overall_time_interval,
      minute_of_end_overall_time_interval: minute_of_end_overall_time_interval,
      second_of_end_of_overall_time_interval: second_of_end_of_overall_time_interval,
      n_number_of_time_range_specifications_describing_the_time_intervals_used_to_calculate_the_statistically_processed_field:
        n_number_of_time_range_specifications_describing_the_time_intervals_used_to_calculate_the_statistically_processed_field,
      total_number_of_data_values_missing_in_the_statistical_process:
        total_number_of_data_values_missing_in_the_statistical_process,
      statistical_process_used_to_calculate_the_processed_field_from_the_field_at_each_time_increment_during_the_time_range:
        statistical_process_used_to_calculate_the_processed_field_from_the_field_at_each_time_increment_during_the_time_range,
      type_of_time_increment_between_successive_fields_used_in_the_statistical_processing:
        type_of_time_increment_between_successive_fields_used_in_the_statistical_processing,
      indicator_of_unit_of_time_range_over_which_statistical_processing_is_done:
        indicator_of_unit_of_time_range_over_which_statistical_processing_is_done,
      length_of_the_time_range_over_which_statistical_processing_is_done_in_units_defined_by_the_previous_octet:
        length_of_the_time_range_over_which_statistical_processing_is_done_in_units_defined_by_the_previous_octet,
      indicator_of_unit_of_time_for_the_increment_between_the_successive_fields_used:
        indicator_of_unit_of_time_for_the_increment_between_the_successive_fields_used,
      time_increment_between_successive_fields_in_units_defined_by_the_previous_octet:
        time_increment_between_successive_fields_in_units_defined_by_the_previous_octet,
      as_octets: as_octets
    }

    {:ok, template, rest}
  end
end
