defmodule ExGrib.Grib2.Section4.Templates.CategoricalForecasts do
  @moduledoc """
  Template 4.51

  Categorical forecasts at a horizontal levelor in a horizontal layer at a point in time

  Note:  Hours greater than
  65534 will be coded as 65534

  WARNING THIS TEMPLATE WAS AUTOGENERATED AND IS LIKELY INCOMPLETE

  https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_temp4-51.shtml
  """

  defstruct parameter_category: nil,
            parameter_number: nil,
            type_of_generating_process: nil,
            background_generating_process_identifier: nil,
            analysis_or_forecast_generating_process_identifier: nil,
            hours_after_reference_time_of_data_cutoff: nil,
            minutes_after_reference_time_of_data_cutoff: nil,
            indicator_of_unit_of_time_range: nil,
            forecast_time_in_units_defined_by_octet: nil,
            type_of_first_fixed_surface: nil,
            scale_factor_of_first_fixed_surface: nil,
            scaled_value_of_first_fixed_surface: nil,
            type_of_second_fixed_surfaced: nil,
            scale_factor_of_second_fixed_surface: nil,
            scaled_value_of_second_fixed_surfaces: nil,
            nc_number_of_categories: nil,
            code_figure: nil,
            type_of_interval_for_first_and_second_limit: nil,
            scale_factor_of_first_limit: nil,
            scale_value_of_first_limit: nil,
            scale_factor_of_second_limit: nil,
            scale_value_of_second_limit: nil

  @spec get(binary()) :: no_return
  def get(<<
        # Parameter category (see Code table 4.1)
        parameter_category::integer(),
        # Parameter number (see Code table 4.2)
        parameter_number::integer(),
        # Type of generating process (see Code table 4.3)
        type_of_generating_process::integer(),
        # Background generating process identifier (defined by originating centre)
        background_generating_process_identifier::integer(),
        # Analysis or forecast generating process identifier (see Code ON388 Table A)
        analysis_or_forecast_generating_process_identifier::integer(),
        # Hours after reference time of data cutoff (see Note)
        hours_after_reference_time_of_data_cutoff::integer-size(16),
        # Minutes after reference time of data cutoff (see Note)
        minutes_after_reference_time_of_data_cutoff::integer(),
        # Indicator of unit of time range (see Code table 4.4)
        indicator_of_unit_of_time_range::integer(),
        # Forecast time in units defined by octet 18
        forecast_time_in_units_defined_by_octet::integer-size(32),
        # Type of first fixed surface (see Code table 4.5)
        type_of_first_fixed_surface::integer(),
        scale_factor_of_first_fixed_surface::integer(),
        scaled_value_of_first_fixed_surface::integer-size(32),
        # Type of second fixed surfaced (see Code table 4.5)
        type_of_second_fixed_surfaced::integer(),
        scale_factor_of_second_fixed_surface::integer(),
        scaled_value_of_second_fixed_surfaces::integer-size(32),
        # NC  - Number of Categories
        nc_number_of_categories::integer(),
        code_figure::integer-size(28880),
        # Type of interval for first and second limit (see Code table 4.91)
        type_of_interval_for_first_and_second_limit::integer-size(29680),
        scale_factor_of_first_limit::integer-size(30480),
        scale_value_of_first_limit::integer-size(2408),
        scale_factor_of_second_limit::integer-size(34480),
        scale_value_of_second_limit::integer-size(2408),
        rest::binary()
      >>) do
    template = %__MODULE__{
      parameter_category: parameter_category,
      parameter_number: parameter_number,
      type_of_generating_process: type_of_generating_process,
      background_generating_process_identifier: background_generating_process_identifier,
      analysis_or_forecast_generating_process_identifier:
        analysis_or_forecast_generating_process_identifier,
      hours_after_reference_time_of_data_cutoff: hours_after_reference_time_of_data_cutoff,
      minutes_after_reference_time_of_data_cutoff: minutes_after_reference_time_of_data_cutoff,
      indicator_of_unit_of_time_range: indicator_of_unit_of_time_range,
      forecast_time_in_units_defined_by_octet: forecast_time_in_units_defined_by_octet,
      type_of_first_fixed_surface: type_of_first_fixed_surface,
      scale_factor_of_first_fixed_surface: scale_factor_of_first_fixed_surface,
      scaled_value_of_first_fixed_surface: scaled_value_of_first_fixed_surface,
      type_of_second_fixed_surfaced: type_of_second_fixed_surfaced,
      scale_factor_of_second_fixed_surface: scale_factor_of_second_fixed_surface,
      scaled_value_of_second_fixed_surfaces: scaled_value_of_second_fixed_surfaces,
      nc_number_of_categories: nc_number_of_categories,
      code_figure: code_figure,
      type_of_interval_for_first_and_second_limit: type_of_interval_for_first_and_second_limit,
      scale_factor_of_first_limit: scale_factor_of_first_limit,
      scale_value_of_first_limit: scale_value_of_first_limit,
      scale_factor_of_second_limit: scale_factor_of_second_limit,
      scale_value_of_second_limit: scale_value_of_second_limit
    }

    {:ok, template, rest}
  end
end
