defmodule ExGrib.Grib2.Section4.Templates.CcittIa5CharacterString do
  @moduledoc """
  Template 4.254

  Ccitt ia5 character string

  WARNING THIS TEMPLATE WAS AUTOGENERATED AND IS LIKELY INCOMPLETE

  https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_temp4-254.shtml
  """

  defstruct parameter_category: nil, parameter_number: nil, number_of_characters: nil

  @spec get(binary()) :: no_return
  def get(<<
        # Parameter category (see Code Table 4.1)
        parameter_category::integer(),
        # Parameter number (see Code Table 4.2)
        parameter_number::integer(),
        number_of_characters::integer-size(32),
        rest::binary()
      >>) do
    template = %__MODULE__{
      parameter_category: parameter_category,
      parameter_number: parameter_number,
      number_of_characters: number_of_characters
    }

    {:ok, template, rest}
  end
end
