defmodule ExGrib.Grib2.Section4.Templates.IndividualEnsembleForecastControlAndPerturbedAtIntervalsForAtmosphericChemicalConstituentsBasedOnADistributionFunction do
  @moduledoc """
  Template 4.68

  Individual ensemble forecast control and perturbed at intervals for atmospheric chemical constituents based on a distribution functiontime intervalfor atmospheric chemical constituents based on a distribution function

  Notes:
  1. If Number of mode (N) > 1, then between X N fields with mode number I=1,...,N define the distribution function. X is number of variable
  parameters in the distribution function.
  2. For more information, see Part B, GRIB Attachment III.
  3. Hours greater than 65534 will be coded as 65534.
  4. The reference time in section 1 and the forecast time together define the beginning of the overall time interval.
  5. An increment of zero means that the statistical processing is the result of a continuous (or near continuous) process,
  not the processing of a number of discrete samples. Examples of such continuous processes are the temperatures measured
  by analogue maximum and minimum thermometers or thermographs, and the rainfall measured by a rain gauge.
  6. The reference and forecast times are successively set to their initial values plus or minus the increment, as defined
  by the type of time increment. For all but the innermost (last) time range, the next inner range is then processed using
  these reference and forecast times as the initial reference and forecast times.

  WARNING THIS TEMPLATE WAS AUTOGENERATED AND IS LIKELY INCOMPLETE

  https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_temp4-68.shtml
  """

  defstruct parameter_category: nil,
            parameter_number: nil,
            atmospheric_chemical_constituent_type: nil,
            number_of_mode: nil,
            mode_number: nil,
            type_of_distribution_function: nil,
            number_of_following_function_paramters: nil,
            list_of_scale_factor_of_fixed_distribution_function_parameter: nil,
            list_of_scale_value_of_fixed_distribution_function_parameter: nil,
            type_of_generting_process: nil,
            background_generting_process_identifier: nil,
            analysis_or_forecast_generating_process_identifier: nil,
            hours_of_observational_data_cut_off_after_reference_time: nil,
            minutes_of_observational_data_cut_off_after_reference_time: nil,
            indicator_of_unit_of_time_range: nil,
            forecast_time_in_units_defined_by_previous_octet: nil,
            type_of_first_fixed_surface: nil,
            scale_factor_of_first_fixed_surface: nil,
            scale_value_of_first_fixed_surface: nil,
            type_of_first_second_surface: nil,
            scale_factor_of_second_fixed_surface: nil,
            scale_value_of_second_fixed_surface: nil,
            type_of_ensemble_forecast: nil,
            perturbation_number: nil,
            number_of_forecasts_in_ensemble: nil,
            year_of_time_of_end_of_overall_time_interval: nil,
            month_of_time_of_end_of_overall_time_interval: nil,
            day_of_time_of_end_of_overall_time_interval: nil,
            hour_of_time_of_end_of_overall_time_interval: nil,
            minute_of_time_of_end_of_overall_time_interval: nil,
            second_of_time_of_end_of_overall_time_interval: nil,
            n_number_of_time_range_specifications_describing_the_time_intervals_used_to_calculate_the_statistically_processed_field:
              nil,
            total_number_of_data_values_missing_in_statistical_process: nil,
            statistical_process_used_to_calculate_the_processed_field_from_the_field_at_each_time_increment_during_the_time_range:
              nil,
            type_of_time_increment_between_successive_fields_used_in_the_statistical_processing:
              nil,
            indicator_of_unit_of_time_for_time_range_over_which_statistical_processing_is_done:
              nil,
            length_of_the_time_range_over_which_statistical_processing_is_done_in_units_defined_by_the_previous_octet:
              nil,
            indicator_of_unit_of_time_for_the_increment_between_the_successive_fields_used: nil,
            also_length_of_the_time_range_over_which_statistical_processing_is_done_in_units_defined_by_the_previous_octet:
              nil,
            as_octets: nil

  @spec get(binary()) :: no_return
  def get(<<
        # Parameter category (see Code Table 4.1)
        parameter_category::integer(),
        # Parameter number (see Code Table 4.2)
        parameter_number::integer(),
        # Atmospheric Chemical Constituent Type (see Code table 4.230)
        atmospheric_chemical_constituent_type::integer-size(16),
        # Number of mode (N) of distribution (See Note 2)
        number_of_mode::integer-size(16),
        # Mode number (l)
        mode_number::integer-size(16),
        # Type of distribution function (see Code Table 4.240)
        type_of_distribution_function::integer-size(16),
        # Number of following function paramters (Np) defined by type given in octet 18-19 (Type of distribution function)
        number_of_following_function_paramters::integer(),
        # List of scale factor of fixed distribution function parameter (p1 -  pNp) defined by type of distribution in octet 18-19
        list_of_scale_factor_of_fixed_distribution_function_parameter::integer-size(1704),
        # List of scale value of fixed distribution function parameter (p1 -  pNp) defined by type of distribution in octet 18-19
        list_of_scale_value_of_fixed_distribution_function_parameter::integer-size(248),
        # Type of generting process (see Code Table 4.3)
        type_of_generting_process::integer(),
        # Background generting process identifier (defined by originating centre)
        background_generting_process_identifier::integer(),
        # Analysis or forecast generating process identifier (defined by originating centre)
        analysis_or_forecast_generating_process_identifier::integer(),
        # Hours of observational data cut-off after reference time (See Note 1)
        hours_of_observational_data_cut_off_after_reference_time::integer-size(88),
        minutes_of_observational_data_cut_off_after_reference_time::integer(),
        # Indicator of unit of time range (see Code Table 4.4)
        indicator_of_unit_of_time_range::integer(),
        forecast_time_in_units_defined_by_previous_octet::integer-size(248),
        # Type of first fixed surface (see Code Table 4.5)
        type_of_first_fixed_surface::integer(),
        scale_factor_of_first_fixed_surface::integer(),
        scale_value_of_first_fixed_surface::integer-size(248),
        # Type of first second surface (see Code Table 4.5)
        type_of_first_second_surface::integer(),
        scale_factor_of_second_fixed_surface::integer(),
        scale_value_of_second_fixed_surface::integer-size(248),
        # Type of Ensemble Forecast (see Code Table 4.6)
        type_of_ensemble_forecast::integer(),
        perturbation_number::integer(),
        number_of_forecasts_in_ensemble::integer(),
        year_of_time_of_end_of_overall_time_interval::integer-size(88),
        month_of_time_of_end_of_overall_time_interval::integer(),
        day_of_time_of_end_of_overall_time_interval::integer(),
        hour_of_time_of_end_of_overall_time_interval::integer(),
        minute_of_time_of_end_of_overall_time_interval::integer(),
        second_of_time_of_end_of_overall_time_interval::integer(),
        # n – number of time range specifications describing the time intervals used to calculate the statistically processed field
        n_number_of_time_range_specifications_describing_the_time_intervals_used_to_calculate_the_statistically_processed_field::integer(),
        total_number_of_data_values_missing_in_statistical_process::integer-size(248),
        # Statistical process used to calculate the processed field from the field at each time increment during the time range (see Code Table 4.10)
        statistical_process_used_to_calculate_the_processed_field_from_the_field_at_each_time_increment_during_the_time_range::integer(),
        # Type of time increment between successive fields used in the statistical processing (see Code Table 4.11)
        type_of_time_increment_between_successive_fields_used_in_the_statistical_processing::integer(),
        # Indicator of unit of time for time range over which statistical processing is done (see Code Table 4.4)
        indicator_of_unit_of_time_for_time_range_over_which_statistical_processing_is_done::integer(),
        length_of_the_time_range_over_which_statistical_processing_is_done_in_units_defined_by_the_previous_octet::integer-size(
          248
        ),
        # Indicator of unit of time for the increment between the successive fields used (see Code Table 4.4)
        indicator_of_unit_of_time_for_the_increment_between_the_successive_fields_used::integer(),
        also_length_of_the_time_range_over_which_statistical_processing_is_done_in_units_defined_by_the_previous_octet::integer-size(
          248
        ),
        # As octets (59+5Np) to (70+5Np) next innermost step of processing
        as_octets::integer-size(888),
        # Additional time range specifications included in accordance with the value of n. Contents as octets (59+5Np) to (70+5Np) repeated as necessary
        rest::binary()
      >>) do
    template = %__MODULE__{
      parameter_category: parameter_category,
      parameter_number: parameter_number,
      atmospheric_chemical_constituent_type: atmospheric_chemical_constituent_type,
      number_of_mode: number_of_mode,
      mode_number: mode_number,
      type_of_distribution_function: type_of_distribution_function,
      number_of_following_function_paramters: number_of_following_function_paramters,
      list_of_scale_factor_of_fixed_distribution_function_parameter:
        list_of_scale_factor_of_fixed_distribution_function_parameter,
      list_of_scale_value_of_fixed_distribution_function_parameter:
        list_of_scale_value_of_fixed_distribution_function_parameter,
      type_of_generting_process: type_of_generting_process,
      background_generting_process_identifier: background_generting_process_identifier,
      analysis_or_forecast_generating_process_identifier:
        analysis_or_forecast_generating_process_identifier,
      hours_of_observational_data_cut_off_after_reference_time:
        hours_of_observational_data_cut_off_after_reference_time,
      minutes_of_observational_data_cut_off_after_reference_time:
        minutes_of_observational_data_cut_off_after_reference_time,
      indicator_of_unit_of_time_range: indicator_of_unit_of_time_range,
      forecast_time_in_units_defined_by_previous_octet:
        forecast_time_in_units_defined_by_previous_octet,
      type_of_first_fixed_surface: type_of_first_fixed_surface,
      scale_factor_of_first_fixed_surface: scale_factor_of_first_fixed_surface,
      scale_value_of_first_fixed_surface: scale_value_of_first_fixed_surface,
      type_of_first_second_surface: type_of_first_second_surface,
      scale_factor_of_second_fixed_surface: scale_factor_of_second_fixed_surface,
      scale_value_of_second_fixed_surface: scale_value_of_second_fixed_surface,
      type_of_ensemble_forecast: type_of_ensemble_forecast,
      perturbation_number: perturbation_number,
      number_of_forecasts_in_ensemble: number_of_forecasts_in_ensemble,
      year_of_time_of_end_of_overall_time_interval: year_of_time_of_end_of_overall_time_interval,
      month_of_time_of_end_of_overall_time_interval:
        month_of_time_of_end_of_overall_time_interval,
      day_of_time_of_end_of_overall_time_interval: day_of_time_of_end_of_overall_time_interval,
      hour_of_time_of_end_of_overall_time_interval: hour_of_time_of_end_of_overall_time_interval,
      minute_of_time_of_end_of_overall_time_interval:
        minute_of_time_of_end_of_overall_time_interval,
      second_of_time_of_end_of_overall_time_interval:
        second_of_time_of_end_of_overall_time_interval,
      n_number_of_time_range_specifications_describing_the_time_intervals_used_to_calculate_the_statistically_processed_field:
        n_number_of_time_range_specifications_describing_the_time_intervals_used_to_calculate_the_statistically_processed_field,
      total_number_of_data_values_missing_in_statistical_process:
        total_number_of_data_values_missing_in_statistical_process,
      statistical_process_used_to_calculate_the_processed_field_from_the_field_at_each_time_increment_during_the_time_range:
        statistical_process_used_to_calculate_the_processed_field_from_the_field_at_each_time_increment_during_the_time_range,
      type_of_time_increment_between_successive_fields_used_in_the_statistical_processing:
        type_of_time_increment_between_successive_fields_used_in_the_statistical_processing,
      indicator_of_unit_of_time_for_time_range_over_which_statistical_processing_is_done:
        indicator_of_unit_of_time_for_time_range_over_which_statistical_processing_is_done,
      length_of_the_time_range_over_which_statistical_processing_is_done_in_units_defined_by_the_previous_octet:
        length_of_the_time_range_over_which_statistical_processing_is_done_in_units_defined_by_the_previous_octet,
      indicator_of_unit_of_time_for_the_increment_between_the_successive_fields_used:
        indicator_of_unit_of_time_for_the_increment_between_the_successive_fields_used,
      also_length_of_the_time_range_over_which_statistical_processing_is_done_in_units_defined_by_the_previous_octet:
        also_length_of_the_time_range_over_which_statistical_processing_is_done_in_units_defined_by_the_previous_octet,
      as_octets: as_octets
    }

    {:ok, template, rest}
  end
end
