defmodule ExGrib.Grib2.Section4.Templates.IndividualEnsembleForecastControlAndPerturbedAtIntervalsForSimulated do
  @moduledoc """
  Template 4.34

  Individual ensemble forecast control and perturbed at intervals for simulatedr in a horizontal layer, in a continuous or  non-continuous interval forsimulated (synthetic) satellite data

  WARNING THIS TEMPLATE WAS AUTOGENERATED AND IS LIKELY INCOMPLETE

  https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_temp4-34.shtml
  """

  defstruct parameter_category: nil,
            parameter_number: nil,
            type_of_generating_process: nil,
            background_generating_process_identifier: nil,
            analysis_or_forecast_generating_process_identified: nil,
            hours_of_observational_data_cut_off_after_reference_time: nil,
            minutes_of_observational_data_cut_off_after_reference_time: nil,
            indicator_of_unit_of_time_range: nil,
            forecast_time_in_units_defined_by_octet: nil,
            number_of_contributing_spectral_bands: nil,
            satellite_series_of_band_nb: nil,
            satellite_number_of_band_nb: nil,
            instrument_types_of_band_nb: nil,
            scale_factor_of_central_wave_number_of_band_nb: nil,
            scaled_value_of_central_wave_number_of_band_nb: nil,
            type_of_ensemble_forecast: nil,
            perturbation_number: nil,
            number_of_forecast_in_ensemble: nil,
            year_of_end_of_overall_time_interval: nil,
            month_of_end_of_overall_time_interval: nil,
            day_of_end_of_overall_time_interval: nil,
            hour_of_end_of_overall_time_interval: nil,
            minute_of_end_of_overall_time_interval: nil,
            second_of_end_of_overall_time_interval: nil,
            n_number_of_time_range_specifications_describing_the_time_interval_used_to_calculate_the_statistically_processed_field:
              nil,
            total_number_of_data_values_missing_in_statistical_process: nil

  @spec get(binary()) :: no_return
  def get(<<
        # Parameter category (see Code Table 4.1)
        parameter_category::integer(),
        # Parameter number (see Code Table 4.2)
        parameter_number::integer(),
        # Type of generating process (see Code Table 4.3)
        type_of_generating_process::integer(),
        # Background generating process identifier (defined by originating centres)
        background_generating_process_identifier::integer(),
        analysis_or_forecast_generating_process_identified::integer(),
        # Hours of observational data cut-off after reference time (see Note 2)
        hours_of_observational_data_cut_off_after_reference_time::integer-size(16),
        # Minutes of observational data cut-off after reference time (see Note 2)
        minutes_of_observational_data_cut_off_after_reference_time::integer(),
        # Indicator of unit of time range (see Code Table 4.4)
        indicator_of_unit_of_time_range::integer(),
        # Forecast time in units defined by octet 18
        forecast_time_in_units_defined_by_octet::integer-size(32),
        # Number of contributing spectral bands (NB)
        number_of_contributing_spectral_bands::integer(),
        # Satellite series of band nb (BUFR Code Table 0 02 020)
        satellite_series_of_band_nb::integer-size(80808),
        # Satellite number of band nb (BUFR Code Table 0 01 007)
        satellite_number_of_band_nb::integer-size(80808),
        # Instrument types of band nb (see Note 5 below)
        instrument_types_of_band_nb::integer-size(80808),
        scale_factor_of_central_wave_number_of_band_nb::integer-size(24072),
        # Scaled value of central wave number of band nb (units: m-1)
        scaled_value_of_central_wave_number_of_band_nb::integer-size(82408),
        # Type of ensemble forecast (see Code Table 4.6)
        type_of_ensemble_forecast::integer(),
        perturbation_number::integer(),
        number_of_forecast_in_ensemble::integer(),
        year_of_end_of_overall_time_interval::integer(),
        month_of_end_of_overall_time_interval::integer(),
        day_of_end_of_overall_time_interval::integer(),
        hour_of_end_of_overall_time_interval::integer(),
        minute_of_end_of_overall_time_interval::integer(),
        second_of_end_of_overall_time_interval::integer(),
        # n - number of time range specifications describing the time interval used to calculate the statistically processed field
        n_number_of_time_range_specifications_describing_the_time_interval_used_to_calculate_the_statistically_processed_field::integer(),
        total_number_of_data_values_missing_in_statistical_process::integer(),
        rest::binary()
      >>) do
    template = %__MODULE__{
      parameter_category: parameter_category,
      parameter_number: parameter_number,
      type_of_generating_process: type_of_generating_process,
      background_generating_process_identifier: background_generating_process_identifier,
      analysis_or_forecast_generating_process_identified:
        analysis_or_forecast_generating_process_identified,
      hours_of_observational_data_cut_off_after_reference_time:
        hours_of_observational_data_cut_off_after_reference_time,
      minutes_of_observational_data_cut_off_after_reference_time:
        minutes_of_observational_data_cut_off_after_reference_time,
      indicator_of_unit_of_time_range: indicator_of_unit_of_time_range,
      forecast_time_in_units_defined_by_octet: forecast_time_in_units_defined_by_octet,
      number_of_contributing_spectral_bands: number_of_contributing_spectral_bands,
      satellite_series_of_band_nb: satellite_series_of_band_nb,
      satellite_number_of_band_nb: satellite_number_of_band_nb,
      instrument_types_of_band_nb: instrument_types_of_band_nb,
      scale_factor_of_central_wave_number_of_band_nb:
        scale_factor_of_central_wave_number_of_band_nb,
      scaled_value_of_central_wave_number_of_band_nb:
        scaled_value_of_central_wave_number_of_band_nb,
      type_of_ensemble_forecast: type_of_ensemble_forecast,
      perturbation_number: perturbation_number,
      number_of_forecast_in_ensemble: number_of_forecast_in_ensemble,
      year_of_end_of_overall_time_interval: year_of_end_of_overall_time_interval,
      month_of_end_of_overall_time_interval: month_of_end_of_overall_time_interval,
      day_of_end_of_overall_time_interval: day_of_end_of_overall_time_interval,
      hour_of_end_of_overall_time_interval: hour_of_end_of_overall_time_interval,
      minute_of_end_of_overall_time_interval: minute_of_end_of_overall_time_interval,
      second_of_end_of_overall_time_interval: second_of_end_of_overall_time_interval,
      n_number_of_time_range_specifications_describing_the_time_interval_used_to_calculate_the_statistically_processed_field:
        n_number_of_time_range_specifications_describing_the_time_interval_used_to_calculate_the_statistically_processed_field,
      total_number_of_data_values_missing_in_statistical_process:
        total_number_of_data_values_missing_in_statistical_process
    }

    {:ok, template, rest}
  end
end
