defmodule ExGrib.Grib2.Section4.Templates.RadarProduct do
  @moduledoc """
  Template 4.20

  Radar product

  WARNING THIS TEMPLATE WAS AUTOGENERATED AND IS LIKELY INCOMPLETE

  https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_temp4-20.shtml
  """

  defstruct parameter_category: nil,
            parameter_number: nil,
            type_of_generating_process: nil,
            number_of_radar_sites_used: nil,
            indicator_of_unit_time_range: nil,
            site_latitude: nil,
            site_longitude: nil,
            site_elevation: nil,
            site_id_alphanumeric: nil,
            site_id: nil,
            operating_mode: nil,
            reflectivity_calibration_constant: nil,
            quality_control_indicator: nil,
            clutter_filter_indicator: nil,
            constant_antenna_elevation_angle: nil,
            accumulation_interval: nil,
            reference_reflectivity_for_echo_top: nil,
            range_bin_spacing: nil,
            radial_angular_spacing: nil

  @spec get(binary()) :: no_return
  def get(<<
        # Parameter category (see Code Table 4.1)
        parameter_category::integer(),
        # Parameter number (see Code Table 4.2)
        parameter_number::integer(),
        # Type of generating process (see Code Table 4.3)
        type_of_generating_process::integer(),
        number_of_radar_sites_used::integer(),
        indicator_of_unit_time_range::integer(),
        # Site latitude (in 10-6 degree)
        site_latitude::integer-size(32),
        # Site longitude (in 10-6 degree)
        site_longitude::integer-size(32),
        # Site elevation (metres)
        site_elevation::integer-size(16),
        # Site ID (alphanumeric)
        site_id_alphanumeric::integer-size(32),
        # Site ID (numeric)
        site_id::integer-size(16),
        # Operating mode (see Code Table 4.12)
        operating_mode::integer(),
        # Reflectivity calibration constant (tenths of dB)
        reflectivity_calibration_constant::integer(),
        # Quality control indicator (see Code Table 4.13)
        quality_control_indicator::integer(),
        # Clutter filter indicator (see Code Table 4.14)
        clutter_filter_indicator::integer(),
        # Constant antenna elevation angle (tenths of degree true)
        constant_antenna_elevation_angle::integer(),
        # Accumulation interval (minutes)
        accumulation_interval::integer-size(16),
        # Reference reflectivity for echo top (dB)
        reference_reflectivity_for_echo_top::integer(),
        # Range bin spacing (metres)
        range_bin_spacing::integer-size(24),
        # Radial angular spacing (tenths of degree true)
        radial_angular_spacing::integer-size(16),
        rest::binary()
      >>) do
    template = %__MODULE__{
      parameter_category: parameter_category,
      parameter_number: parameter_number,
      type_of_generating_process: type_of_generating_process,
      number_of_radar_sites_used: number_of_radar_sites_used,
      indicator_of_unit_time_range: indicator_of_unit_time_range,
      site_latitude: site_latitude,
      site_longitude: site_longitude,
      site_elevation: site_elevation,
      site_id_alphanumeric: site_id_alphanumeric,
      site_id: site_id,
      operating_mode: operating_mode,
      reflectivity_calibration_constant: reflectivity_calibration_constant,
      quality_control_indicator: quality_control_indicator,
      clutter_filter_indicator: clutter_filter_indicator,
      constant_antenna_elevation_angle: constant_antenna_elevation_angle,
      accumulation_interval: accumulation_interval,
      reference_reflectivity_for_echo_top: reference_reflectivity_for_echo_top,
      range_bin_spacing: range_bin_spacing,
      radial_angular_spacing: radial_angular_spacing
    }

    {:ok, template, rest}
  end
end
