defmodule ExGrib.Grib2.Section4.Templates.SatelliteProductWithOrWithoutAssociatedQualityValues do
  @moduledoc """
  Template 4.35

  Satellite product with or without associated quality values

  Note :

  For “satellite series of band nb”, “satellite numbers of band nb” and “instrument types of band nb”,
  it is recommended to encode the values as per BUFR Code tables 0 02 020, 0 01 007 (Common Code table C–5)
  and 0 02 019 (Common Code table C–8), respectively.

  WARNING THIS TEMPLATE WAS AUTOGENERATED AND IS LIKELY INCOMPLETE

  https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_temp4-35.shtml
  """

  defstruct parameter_category: nil,
            parameter_number: nil,
            type_of_generating_process: nil,
            observation_generating_process_identifier: nil,
            quality_value_associated_with_parameter: nil,
            number_of_contributing_spectral_bands: nil,
            satellite_series_of_band_nb: nil,
            satellite_number_of_band_nb: nil,
            instrument_types_of_band_nb: nil,
            scale_factor_of_central_wave_number_of_band_nb: nil,
            scaled_value_of_central_wave_number_of_band_nb: nil

  @spec get(binary()) :: no_return
  def get(<<
        # Parameter category (see Code Table 4.1)
        parameter_category::integer(),
        # Parameter number (see Code Table 4.2)
        parameter_number::integer(),
        # Type of generating process (see Code Table 4.3)
        type_of_generating_process::integer(),
        # Observation generating process identifier (defined by originating centres)
        observation_generating_process_identifier::integer(),
        # Quality value associated with parameter (see Code Table 4.16)
        quality_value_associated_with_parameter::integer(),
        # Number of contributing spectral bands (NB)
        number_of_contributing_spectral_bands::integer(),
        # Satellite series of band nb ( code table defined by originating generating centre)
        satellite_series_of_band_nb::integer-size(80808),
        # Satellite number of band nb (code table defined by originating generating centre)
        satellite_number_of_band_nb::integer-size(80808),
        # Instrument types of band nb (code table defined by originating generating centre)
        instrument_types_of_band_nb::integer-size(80808),
        scale_factor_of_central_wave_number_of_band_nb::integer-size(17672),
        # Scaled value of central wave number of band nb (units: m-1)
        scaled_value_of_central_wave_number_of_band_nb::integer-size(82408),
        rest::binary()
      >>) do
    template = %__MODULE__{
      parameter_category: parameter_category,
      parameter_number: parameter_number,
      type_of_generating_process: type_of_generating_process,
      observation_generating_process_identifier: observation_generating_process_identifier,
      quality_value_associated_with_parameter: quality_value_associated_with_parameter,
      number_of_contributing_spectral_bands: number_of_contributing_spectral_bands,
      satellite_series_of_band_nb: satellite_series_of_band_nb,
      satellite_number_of_band_nb: satellite_number_of_band_nb,
      instrument_types_of_band_nb: instrument_types_of_band_nb,
      scale_factor_of_central_wave_number_of_band_nb:
        scale_factor_of_central_wave_number_of_band_nb,
      scaled_value_of_central_wave_number_of_band_nb:
        scaled_value_of_central_wave_number_of_band_nb
    }

    {:ok, template, rest}
  end
end
